---
title: "NFWBS Blog"
author: "Cody Tuttle"
date: "1/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Hello everyone! Welcome back to my blog - it's been way too long, I know, but I'm back for a post before I start my new semester (my final semester of grad school HALLELUJAH!!!). As much as I want to update you on my life and everything, I'm going to skip the pleasantries and just get straight to the post. 


```{r}
data <- read.csv("/Users/codytuttle/Desktop/cfpb_blog/cfpb_clean.csv")

library("pacman")

p_load(tidyverse, survey, srvyr)


```


```{r}

dw <- svydesign(ids = data$PUF_ID, data = data, weights = data$finalwt)

prop.table(table(data$PPETHM))

prop.table(svytable(~PPETHM, design = dw))
```


```{r}

weighted <- data %>%
  as_survey(PUF_ID, weight = finalwt)

weighted %>%
  group_by(PPETHM, fpl) %>%
  summarize(finscore = survey_mean(as.numeric(FWBscore))) %>%
  ggplot(aes(x = PPETHM, y = finscore, group = fpl, fill = fpl)) +
    geom_bar(stat = "identity", position = "dodge")

weighted %>%
  group_by(PPETHM, fpl) %>%
  summarize(fsscore = survey_mean(as.numeric(FSscore))) %>%
  ggplot(aes(x = PPETHM, y = fsscore, group = fpl, fill = fpl)) +
    geom_bar(stat = "identity", position = "dodge")

weighted %>%
  group_by(PPETHM, fpl) %>%
  mutate(rejected = ifelse(REJECTED_1 == "Yes", 1, 
                           ifelse(REJECTED_1 == "No", 0, 99))) %>%
  filter(rejected != 99) %>%
  summarize(rejected = survey_mean(rejected)) %>%
  ggplot(aes(x = PPETHM, y = (100*rejected), group = fpl, fill = fpl)) +
    geom_bar(stat = "identity", position = "dodge")
    

prop.table(table(data$REJECTED_1))

```

